name: Deploy vkaagroproducts.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: pdo_sqlite, fileinfo, mbstring

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev

    - name: Setup Node.js (For Blade Vite Assets)
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install NPM & Compile Styles
      run: |
        npm ci
        npm run build

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/vkaagroproducts.com/